# Generated by Django 6.0.6 on 2026-06-23 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0010_presupuesto_completed_at_presupuesto_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, help_text='Si está inactiva, no se le asignan trabajos nuevos ni cuenta para la cola.', verbose_name='Activa')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
            ],
            options={
                'verbose_name': 'Máquina (impresora)',
                'verbose_name_plural': 'Máquinas (impresoras)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad de piezas')),
                ('order', models.PositiveIntegerField(default=0, help_text='Posición dentro de la cola de la máquina (menor = primero).', verbose_name='Orden en la cola')),
                ('status', models.CharField(choices=[('PENDING', 'En cola'), ('PRINTING', 'Imprimiendo'), ('DONE', 'Impreso'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('estimated_start', models.DateTimeField(blank=True, null=True, verbose_name='Inicio estimado')),
                ('estimated_print_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin de impresión estimado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicio real')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin real')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('machine', models.ForeignKey(blank=True, help_text='Máquina asignada. El sistema recomienda una, podés cambiarla.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='production.maquina', verbose_name='Máquina')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='budgets.presupuesto', verbose_name='Presupuesto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='budgets.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Trabajo de producción',
                'verbose_name_plural': 'Trabajos de producción',
                'ordering': ['machine', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ColaProduccion',
            fields=[
            ],
            options={
                'verbose_name': 'Cola de producción',
                'verbose_name_plural': 'Cola de producción',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('production.productionjob',),
        ),
    ]
