# Generated by Django 6.0.6 on 2026-06-23 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
            ],
            options={
                'verbose_name': 'Tablero de producción',
                'verbose_name_plural': 'Tablero de producción',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('production.productionjob',),
        ),
    ]
