# Generated by Django 6.0.6 on 2026-06-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_tablero'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionjob',
            name='stock_consumed',
            field=models.BooleanField(default=False, help_text='Se marca solo cuando el trabajo se imprime y se descuenta el material.', verbose_name='Stock descontado'),
        ),
    ]
