# Generated by Django 6.0.6 on 2026-06-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productionjob_stock_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='supports_multicolor',
            field=models.BooleanField(default=False, help_text='Marcá si la máquina puede imprimir piezas de varios colores en simultáneo (ej. Bambu Lab con AMS). La Ender no lo soporta.', verbose_name='Imprime multicolor (AMS)'),
        ),
    ]
