# Generated by Django 6.0.6 on 2026-06-23 22:22

from django.db import migrations


def set_bambu_multicolor(apps, schema_editor):
    """Las Bambu Lab (con AMS) imprimen multicolor; la Ender no."""
    Maquina = apps.get_model("production", "Maquina")
    Maquina.objects.filter(name__icontains="bambu").update(supports_multicolor=True)


def unset_multicolor(apps, schema_editor):
    Maquina = apps.get_model("production", "Maquina")
    Maquina.objects.all().update(supports_multicolor=False)


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_maquina_supports_multicolor'),
    ]

    operations = [
        migrations.RunPython(set_bambu_multicolor, unset_multicolor),
    ]
