# Generated by Django 6.0.6 on 2026-06-25 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0016_presupuesto_stock_provisioned'),
        ('production', '0005_set_bambu_multicolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionjob',
            name='pieza',
            field=models.ForeignKey(blank=True, help_text='Pieza concreta que imprime este trabajo. Si está vacío es un trabajo a nivel producto (modo anterior).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='budgets.pieza', verbose_name='Pieza'),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='surplus_added',
            field=models.BooleanField(default=False, help_text='Se marca cuando, al imprimirse, la sobrante del último gcode se sumó al stock de la pieza.', verbose_name='Sobrante sumado a stock'),
        ),
        migrations.AlterField(
            model_name='productionjob',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Unidades de la pieza que hay que imprimir para este pedido.', verbose_name='Cantidad de piezas a imprimir'),
        ),
        migrations.AlterField(
            model_name='productionjob',
            name='stock_consumed',
            field=models.BooleanField(default=False, help_text='Se marca cuando se descontó el filamento de este trabajo (al aprobar el pedido).', verbose_name='Material descontado'),
        ),
    ]
