# Generated by Django 6.0.6 on 2026-06-26 00:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_productionjob_pieza_productionjob_surplus_added_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionjob',
            options={'ordering': ['machine', 'producto__priority', 'order', 'id'], 'verbose_name': 'Trabajo de producción', 'verbose_name_plural': 'Trabajos de producción'},
        ),
        migrations.AddField(
            model_name='maquina',
            name='cost_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Costo horario de la máquina (amortización, energía, mantenimiento). Se usa para calcular la depreciación acumulada: horas impresas × este costo.', max_digits=10, verbose_name='Costo por hora ($/h)'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='total_hours_printed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Horas de impresión de los trabajos ya terminados en esta máquina. Se recalcula automáticamente al marcar un trabajo como Impreso.', max_digits=12, verbose_name='Horas impresas (acumuladas)'),
        ),
    ]
