# Generated by Django 6.0.6 on 2026-06-30 14:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0020_presupuestoitem_from_finished_stock'),
        ('production', '0007_alter_productionjob_options_maquina_cost_per_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionjob',
            name='history_added',
            field=models.BooleanField(default=False, help_text='Se marca cuando, al imprimirse, el trabajo se guardó en el historial de la máquina. Evita duplicar el registro.', verbose_name='Guardado en el historial'),
        ),
        migrations.CreateModel(
            name='HistorialImpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('horas_impresion', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Horas de impresión')),
                ('finalizado_el', models.DateTimeField(verbose_name='Finalizado el')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='production.maquina', verbose_name='Máquina')),
                ('presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='budgets.presupuesto', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Impresión del historial',
                'verbose_name_plural': 'Historial de impresiones',
                'ordering': ['-finalizado_el'],
            },
        ),
    ]
