# Generated by Django 6.0.6 on 2026-06-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_productionjob_history_added_historialimpresion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialimpresion',
            name='estado',
            field=models.CharField(choices=[('IMPRESO', 'Impreso'), ('CANCELADO', 'Cancelado')], default='IMPRESO', max_length=10, verbose_name='Estado'),
        ),
    ]
