# Generated by Django 6.0.6 on 2026-09-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_historialimpresion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionjob',
            name='completed_runs',
            field=models.PositiveIntegerField(default=0, help_text='Cuántas corridas de gcode de este trabajo ya se imprimieron. Se actualiza con el botón "Corrida terminada" de la cola/tablero; al llegar al total de corridas necesarias el trabajo pasa a Impreso.', verbose_name='Corridas de gcode terminadas'),
        ),
    ]
