# Generated by Django 6.0.6 on 2026-09-30 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_productionjob_completed_runs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramoImpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.PositiveIntegerField(default=0, verbose_name='Corridas de gcode')),
                ('is_open', models.BooleanField(default=True, verbose_name='Abierto')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cierre')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='production.productionjob', verbose_name='Trabajo')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='production.maquina', verbose_name='Máquina')),
            ],
            options={
                'verbose_name': 'Tramo de impresión',
                'verbose_name_plural': 'Tramos de impresión',
                'ordering': ['job', 'started_at'],
            },
        ),
    ]
