# Generated by Django 6.0.6 on 2026-10-03 17:13

import django.db.models.deletion
import django.utils.timezone
import production.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_tramoimpresion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerramientaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría de herramienta',
                'verbose_name_plural': 'Categorías de herramienta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Termoformadora de mesa, Sacabocados manual.', max_length=150, verbose_name='Nombre')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de serie')),
                ('ubicacion', models.CharField(blank=True, max_length=150, verbose_name='Ubicación')),
                ('fecha_compra', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de compra')),
                ('proveedor', models.CharField(blank=True, max_length=150, verbose_name='Proveedor')),
                ('costo_adquisicion', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Costo de adquisición ($)')),
                ('comprobante', models.CharField(blank=True, help_text='Referencia del comprobante (ej: "Factura A 0001-00001234"). No se adjunta archivo: lo subido a /media no persiste en producción (Vercel es serverless).', max_length=150, verbose_name='Comprobante / factura')),
                ('medio_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MERCADOPAGO', 'Mercado Pago'), ('UALA', 'Ualá'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], default='', help_text='Cómo se pagó. Efectivo/Transferencia/Mercado Pago/Ualá generan un borrador en el Panel de caja para revisar y confirmar; Tarjeta y cuotas se cargan a mano.', max_length=20, verbose_name='Medio de pago')),
                ('cuota_actual', models.PositiveSmallIntegerField(blank=True, help_text='Si se compró en cuotas, qué número de cuota es este pago puntual (se carga igual que un Gasto: una cuota por pago real).', null=True, verbose_name='Cuota actual')),
                ('cuotas_totales', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cuotas totales')),
                ('se_deprecia', models.BooleanField(default=False, help_text='Activalo solo si este bien tiene valor de reventa y tiene sentido depreciarlo (ej: una termoformadora). Dejalo apagado para herramientas sin valor de reventa (ej: un sacabocados).', verbose_name='Se deprecia')),
                ('vida_util_meses', models.PositiveIntegerField(blank=True, help_text='Requerido si "Se deprecia" está activo.', null=True, verbose_name='Vida útil (meses)')),
                ('valor_residual', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Valor estimado al final de la vida útil (puede ser 0).', max_digits=12, verbose_name='Valor residual ($)')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('REPARACION', 'En reparación'), ('BAJA', 'De baja'), ('VENDIDA', 'Vendida')], default='ACTIVA', max_length=15, verbose_name='Estado')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('motivo_baja', models.CharField(blank=True, max_length=200, verbose_name='Motivo de baja')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, help_text='Si se vendió, cuánto se cobró por ella.', max_digits=12, null=True, verbose_name='Precio de venta ($)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('categoria', models.ForeignKey(default=production.models._default_herramienta_categoria, on_delete=django.db.models.deletion.PROTECT, related_name='herramientas', to='production.herramientacategoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Herramienta / bien de uso',
                'verbose_name_plural': 'Herramientas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Costo ($)')),
                ('proveedor', models.CharField(blank=True, max_length=150, verbose_name='Proveedor / técnico')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='production.herramienta', verbose_name='Herramienta')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
