# Generated by Django 6.0.6 on 2026-06-21 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('category', models.CharField(choices=[('HARDWARE', 'Herraje (argollas, llaveros, etc.)'), ('PACKAGING', 'Packaging'), ('DECORATION', 'Decoración (pegatinas, etc.)'), ('OTHER', 'Otro')], default='OTHER', max_length=20, verbose_name='Categoría')),
                ('unit', models.CharField(choices=[('UNIT', 'Unidad'), ('PAIR', 'Par'), ('METER', 'Metro'), ('GRAM', 'Gramo')], default='UNIT', max_length=10, verbose_name='Unidad')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo por unidad')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock disponible')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Agregado',
                'verbose_name_plural': 'Agregados',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('material_type', models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG'), ('ABS', 'ABS'), ('TPU', 'TPU'), ('ASA', 'ASA'), ('NYLON', 'Nylon'), ('OTHER', 'Otro')], max_length=10, verbose_name='Tipo de material')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('color_hex', models.CharField(blank=True, help_text='Ej: #FF0000. Opcional, para mostrar una muestra de color en el front.', max_length=7, verbose_name='Color (hex)')),
                ('cost_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo por kg')),
                ('stock_grams', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock disponible (g)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Filamento',
                'verbose_name_plural': 'Filamentos',
                'ordering': ['brand', 'material_type', 'color'],
                'constraints': [models.UniqueConstraint(fields=('brand', 'material_type', 'color'), name='unique_filament_brand_material_color')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Negativo = salida de stock. Positivo = entrada de stock.', max_digits=10, verbose_name='Cantidad')),
                ('reason', models.CharField(choices=[('PURCHASE', 'Compra'), ('BUDGET_APPROVED', 'Presupuesto aprobado'), ('MANUAL_ADJUSTMENT', 'Ajuste manual'), ('REPRINT_FAILURE', 'Reimpresión por falla')], max_length=20, verbose_name='Motivo')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('aggregate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.aggregate', verbose_name='Agregado')),
                ('filament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.filament', verbose_name='Filamento')),
                ('related_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='budgets.budget', verbose_name='Presupuesto relacionado')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('aggregate__isnull', True), ('filament__isnull', False)), models.Q(('aggregate__isnull', False), ('filament__isnull', True)), _connector='OR'), name='stock_movement_exactly_one_item')],
            },
        ),
    ]
