# Generated by Django 6.0.6 on 2026-06-23 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTotals',
            fields=[
            ],
            options={
                'verbose_name': 'Totales de inventario',
                'verbose_name_plural': 'Totales de inventario',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.filament',),
        ),
    ]
