# Generated by Django 6.0.6 on 2026-06-23 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktotals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(blank=True, max_length=150, verbose_name='Proveedor')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='N° de factura / remito')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmada el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompraLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Filamento: en gramos. Agregado: en unidades.', max_digits=10, verbose_name='Cantidad comprada')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Filamento: costo por kg. Agregado: costo por unidad. Si se deja vacío, se mantiene el precio actual del artículo.', max_digits=10, null=True, verbose_name='Precio pagado')),
                ('aggregate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compra_lines', to='inventory.aggregate', verbose_name='Agregado')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.compra')),
                ('filament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compra_lines', to='inventory.filament', verbose_name='Filamento')),
            ],
            options={
                'verbose_name': 'Línea de compra',
                'verbose_name_plural': 'Líneas de compra',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('aggregate__isnull', True), ('filament__isnull', False)), models.Q(('aggregate__isnull', False), ('filament__isnull', True)), _connector='OR'), name='compra_line_exactly_one_item')],
            },
        ),
    ]
