# Generated by Django 6.0.6 on 2026-06-23 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_alter_presupuestoitem_producto'),
        ('inventory', '0003_compra_compraline'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='related_presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='budgets.presupuesto', verbose_name='Presupuesto relacionado'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='related_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='budgets.budget', verbose_name='Presupuesto viejo relacionado'),
        ),
    ]
