# Generated by Django 6.0.6 on 2026-06-23 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement_related_presupuesto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='related_budget',
        ),
    ]
