# Generated by Django 6.0.6 on 2026-06-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_stockmovement_related_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteStock',
            fields=[
            ],
            options={
                'verbose_name': 'Ajuste manual de stock',
                'verbose_name_plural': 'Ajustes manuales de stock',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.stockmovement',),
        ),
    ]
