# Generated by Django 6.0.6 on 2026-06-23 20:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_ajustestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregate',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Si el stock baja de este valor, salta la alerta de bajo stock (la campanita). Va en la MISMA unidad del agregado: si se mide en unidades, poné unidades (ej: pelotas → 20); si se mide en gramos, poné gramos (ej: argollas → 200). Poné 0 para no avisar de este agregado.', max_digits=10, verbose_name='Stock mínimo'),
        ),
        migrations.AddField(
            model_name='filament',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000'), help_text='Si el stock baja de este valor, salta la alerta de bajo stock (la campanita). En gramos. Ej: 1000 = 1 kg. Poné 0 para no avisar de este filamento.', max_digits=10, verbose_name='Stock mínimo (g)'),
        ),
    ]
