# Generated by Django 6.0.6 on 2026-06-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_aggregate_min_stock_filament_min_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('PURCHASE', 'Compra'), ('BUDGET_APPROVED', 'Presupuesto aprobado'), ('PRODUCTION', 'Producción (impresión)'), ('MANUAL_ADJUSTMENT', 'Ajuste manual'), ('REPRINT_FAILURE', 'Reimpresión por falla')], max_length=20, verbose_name='Motivo'),
        ),
    ]
