# Generated by Django 6.0.6 on 2026-06-23 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_stockmovement_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='aggregate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.aggregate', verbose_name='Agregado'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='filament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.filament', verbose_name='Filamento'),
        ),
    ]
