# Generated by Django 6.0.6 on 2026-06-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_stockmovement_aggregate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('PURCHASE', 'Compra'), ('BUDGET_APPROVED', 'Presupuesto aprobado'), ('PRODUCTION', 'Producción (impresión)'), ('BUDGET_CANCELLED', 'Cancelación de presupuesto'), ('MANUAL_ADJUSTMENT', 'Ajuste manual'), ('REPRINT_FAILURE', 'Reimpresión por falla')], max_length=20, verbose_name='Motivo'),
        ),
    ]
