# Generated by Django 6.0.6 on 2026-09-29 01:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_aggregate_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregate',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, help_text='Precio en pesos por la unidad que tenga cargada este agregado (el campo Unidad de más arriba: Unidad, Par, Metro o Gramo). Los decimales pueden ir con coma o con punto (12,50 o 12.50).', max_digits=10, verbose_name='Costo por unidad'),
        ),
        migrations.AlterField(
            model_name='aggregate',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Si el stock baja de este valor, salta la alerta de bajo stock (la campanita). Va en la MISMA unidad del agregado: si se mide en unidades, poné unidades (ej: pelotas → 20); si se mide en gramos, poné gramos (ej: argollas → 200). Poné 0 para no avisar de este agregado. Los decimales pueden ir con coma o con punto.', max_digits=10, verbose_name='Stock mínimo'),
        ),
        migrations.AlterField(
            model_name='compraline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Filamento: en GRAMOS (ej: una bobina de 1 kg = 1000). Agregado: en la unidad que tenga cargada (ver su campo Unidad: Unidad, Par, Metro o Gramo). Los decimales pueden ir con coma o con punto.', max_digits=10, verbose_name='Cantidad comprada'),
        ),
        migrations.AlterField(
            model_name='compraline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Filamento: costo por KILOGRAMO (no por gramo ni por bobina). Agregado: costo por la unidad que tenga cargada. Si se deja vacío, se mantiene el precio actual del artículo. Los decimales pueden ir con coma o con punto.', max_digits=10, null=True, verbose_name='Precio pagado'),
        ),
        migrations.AlterField(
            model_name='filament',
            name='cost_per_kg',
            field=models.DecimalField(decimal_places=2, help_text='Precio en pesos por KILOGRAMO (no por gramo ni por bobina). Los decimales pueden ir con coma o con punto (8500,50 u 8500.50).', max_digits=10, verbose_name='Costo por kg'),
        ),
        migrations.AlterField(
            model_name='filament',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000'), help_text='Si el stock baja de este valor, salta la alerta de bajo stock (la campanita). En GRAMOS. Ej: 1000 = 1 kg. Poné 0 para no avisar de este filamento. Los decimales pueden ir con coma o con punto.', max_digits=10, verbose_name='Stock mínimo (g)'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Negativo = salida de stock. Positivo = entrada de stock. Filamento: en gramos. Agregado: en la unidad que tenga cargada (ver su campo Unidad). Los decimales pueden ir con coma o con punto.', max_digits=10, verbose_name='Cantidad'),
        ),
    ]
