# Generated by Django 6.0.6 on 2026-09-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_aggregate_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filament',
            name='notes',
            field=models.TextField(blank=True, help_text='Cosas propias de este filamento: cómo imprime, temperaturas que funcionan bien, si es frágil, proveedor, lote, etc.', verbose_name='Notas'),
        ),
    ]
