# Generated by Django 6.0.6 on 2026-09-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_filament_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregate',
            name='notes',
            field=models.TextField(blank=True, help_text='Cosas propias de este agregado: proveedor, medida exacta, color, dónde se compra, etc.', verbose_name='Notas'),
        ),
    ]
