# Generated by Django 6.0.6 on 2026-10-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_aggregatecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='TOTAL pagado por esta línea completa (no por unidad ni por kg): si compraste 100 argollas por $50.000 en total, cargá 50.000. El sistema divide por la cantidad para calcular el costo unitario (o por kg, para filamento) y actualiza el precio del artículo con ese costo unitario. Si se deja vacío, se mantiene el precio actual del artículo. Los decimales pueden ir con coma o con punto.', max_digits=10, null=True, verbose_name='Precio pagado'),
        ),
    ]
