"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_list(name: str) -> list[str]:
    """Lee una variable de entorno separada por comas como lista limpia."""
    return [item.strip() for item in os.environ.get(name, '').split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En local usa la clave de desarrollo; en producción se toma de SECRET_KEY.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-12eq+f1*t&*e75o#w&0j=3(@99i-+coft%(d=4)%(-n+-6j&x^',
)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG=True por defecto en local; en Vercel se pone DEBUG=0.
DEBUG = os.environ.get('DEBUG', '1') == '1'

# En producción Vercel sirve bajo *.vercel.app (y el dominio propio si se agrega).
ALLOWED_HOSTS = _env_list('ALLOWED_HOSTS') or (['*'] if DEBUG else [])
if not DEBUG:
    ALLOWED_HOSTS += ['.vercel.app']

# CSRF para el admin sobre HTTPS en Vercel.
CSRF_TRUSTED_ORIGINS = _env_list('CSRF_TRUSTED_ORIGINS') or ['https://*.vercel.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'inventory',
    'budgets',
    'production',
    'gastos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # LocaleMiddleware: detecta el idioma (cookie/sesión/Accept-Language) para el
    # selector de idioma del admin. Va DESPUÉS de SessionMiddleware y ANTES de
    # CommonMiddleware.
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Next.js corriendo en local. En producción se suman las URLs vía CORS_ALLOWED_ORIGINS.
CORS_ALLOWED_ORIGINS = _env_list('CORS_ALLOWED_ORIGINS') or [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    # La API solo expone inventario para el front. Por defecto exige estar
    # autenticado como staff (admin); los ViewSets son de solo lectura, así
    # que nadie puede crear/editar/borrar stock vía API.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAdminUser',
    ],
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'inventory.context_processors.low_stock_alerts',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# En local (sin DATABASE_URL) usa SQLite. En Vercel/Neon toma DATABASE_URL.
# conn_max_age=0 porque en serverless cada invocación abre su propia conexión
# (usamos el pooler de Neon). ssl_require para la conexión a Neon.
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=0,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

# Idiomas disponibles en el selector de la navbar del admin. El admin de Django
# trae sus traducciones precompiladas (es/en), y nuestras cadenas propias se
# traducen vía locale/<lang>/LC_MESSAGES/django.mo (ver scripts/compile_messages.py).
# Los nombres van como strings planos (endónimos: cada idioma se muestra en sí
# mismo, no se traducen). NO usar gettext_lazy acá: al leer los settings durante
# el build (Vercel), forzar el proxy dispara la carga de traducciones antes de
# que las apps estén listas → AppRegistryNotReady.
LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'America/Argentina/Cordoba'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Archivos subidos por el usuario (uploads). Por ahora solo para desarrollo
# local: los .3mf / gcode de los productos se guardan en disco. En producción
# (Vercel) el filesystem es efímero; cuando se necesite, migrar a S3/Cloudinary.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise sirve los estáticos del admin en producción (Vercel corre
# collectstatic automáticamente). Comprime y versiona con manifest.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
