# Generated by Django 6.0.6 on 2026-06-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=150, verbose_name='Cliente')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre / pieza')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('print_time_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Tiempo de impresión (hs)')),
                ('machine_cost_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de máquina por hora')),
                ('margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Margen (%)')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviado'), ('APPROVED', 'Aprobado'), ('IN_PRODUCTION', 'En producción'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprobado el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAggregateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Línea de agregado',
                'verbose_name_plural': 'Líneas de agregado',
            },
        ),
        migrations.CreateModel(
            name='BudgetFilamentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gramos usados')),
            ],
            options={
                'verbose_name': 'Línea de filamento',
                'verbose_name_plural': 'Líneas de filamento',
            },
        ),
    ]
