# Generated by Django 6.0.6 on 2026-06-21 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetaggregateline',
            name='aggregate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='inventory.aggregate'),
        ),
        migrations.AddField(
            model_name='budgetaggregateline',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_lines', to='budgets.budget'),
        ),
        migrations.AddField(
            model_name='budgetfilamentline',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filament_lines', to='budgets.budget'),
        ),
        migrations.AddField(
            model_name='budgetfilamentline',
            name='filament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='inventory.filament'),
        ),
    ]
