# Generated by Django 6.0.6 on 2026-06-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetaggregateline',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo por unidad guardado al momento de cotizar. Si se deja vacío, se toma automáticamente el precio actual del agregado. Queda fijo aunque después cambie el precio del agregado.', max_digits=10, null=True, verbose_name='Costo por unidad (congelado)'),
        ),
        migrations.AddField(
            model_name='budgetfilamentline',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Costo por gramo guardado al momento de cotizar. Si se deja vacío, se toma automáticamente el precio actual del filamento. Queda fijo aunque después cambie el precio del filamento.', max_digits=10, null=True, verbose_name='Costo por gramo (congelado)'),
        ),
    ]
