# Generated by Django 6.0.6 on 2026-06-22 13:14

from decimal import Decimal

from django.db import migrations


def backfill_unit_cost(apps, schema_editor):
    """
    Para las líneas que ya existían antes de tener precio congelado,
    guarda el precio vigente del filamento/agregado como su costo congelado,
    para que esos presupuestos no cambien de monto si después varían los precios.
    """
    BudgetFilamentLine = apps.get_model("budgets", "BudgetFilamentLine")
    BudgetAggregateLine = apps.get_model("budgets", "BudgetAggregateLine")

    for line in BudgetFilamentLine.objects.filter(unit_cost__isnull=True).select_related(
        "filament"
    ):
        # cost_per_gram = cost_per_kg / 1000 (replicado: no hay properties en migraciones)
        line.unit_cost = (line.filament.cost_per_kg / Decimal("1000")).quantize(
            Decimal("0.0001")
        )
        line.save(update_fields=["unit_cost"])

    for line in BudgetAggregateLine.objects.filter(unit_cost__isnull=True).select_related(
        "aggregate"
    ):
        line.unit_cost = line.aggregate.cost_per_unit
        line.save(update_fields=["unit_cost"])


def noop_reverse(apps, schema_editor):
    # Revertir solo borraría el dato congelado; lo dejamos como no-op.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_budgetaggregateline_unit_cost_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_unit_cost, noop_reverse),
    ]
