# Generated by Django 6.0.6 on 2026-06-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_backfill_frozen_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='fixed_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo que se cobra una sola vez por pedido (setup, diseño, envío, etc.).', max_digits=10, verbose_name='Costo fijo por pedido'),
        ),
        migrations.AddField(
            model_name='budget',
            name='labor_cost_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de mano de obra por hora'),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_processing_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tiempo de armado, lijado, pintado, pegado de agregados, etc.', max_digits=6, verbose_name='Post-proceso por pieza (hs)'),
        ),
        migrations.AddField(
            model_name='budget',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Cuántas piezas iguales se cotizan. Las líneas de filamento y agregados describen UNA pieza; el costo se multiplica por esta cantidad.', verbose_name='Cantidad de piezas'),
        ),
        migrations.AddField(
            model_name='budget',
            name='round_to',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ej: 100 redondea el total a la centena más cercana. 0 = sin redondeo.', max_digits=10, verbose_name='Redondear total a múltiplo de'),
        ),
        migrations.AddField(
            model_name='budget',
            name='waste_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Desperdicio de filamento por purga (multicolor), soportes y fallas. Se aplica sobre el costo y el consumo de material.', max_digits=5, verbose_name='Merma de material (%)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='print_time_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Tiempo de impresión por pieza (hs)'),
        ),
    ]
