# Generated by Django 6.0.6 on 2026-06-23 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_budget_fixed_cost_budget_labor_cost_per_hour_and_more'),
        ('inventory', '0002_stocktotals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150, verbose_name='Cliente')),
                ('description', models.TextField(blank=True, verbose_name='Notas / descripción')),
                ('fixed_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costo que se cobra una sola vez por pedido (setup, envío, etc.).', max_digits=10, verbose_name='Costo fijo por pedido')),
                ('round_to', models.DecimalField(decimal_places=2, default=0, help_text='Ej: 100 redondea el total a la centena más cercana. 0 = sin redondeo.', max_digits=10, verbose_name='Redondear total a múltiplo de')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviado'), ('APPROVED', 'Aprobado'), ('IN_PRODUCTION', 'En producción'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprobado el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre / pieza')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('print_time_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Tiempo de impresión por pieza (hs)')),
                ('machine_cost_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de máquina por hora')),
                ('waste_percent', models.DecimalField(decimal_places=2, default=0, help_text='Desperdicio de filamento por purga (multicolor), soportes y fallas. Se aplica sobre el costo y el consumo de material.', max_digits=5, verbose_name='Merma de material (%)')),
                ('post_processing_hours', models.DecimalField(decimal_places=2, default=0, help_text='Tiempo de armado, lijado, pintado, pegado de agregados, etc.', max_digits=6, verbose_name='Post-proceso por pieza (hs)')),
                ('labor_cost_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de mano de obra por hora')),
                ('margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Margen (%)')),
                ('round_to', models.DecimalField(decimal_places=2, default=0, help_text='Ej: 100 redondea el precio a la centena más cercana. 0 = sin redondeo.', max_digits=10, verbose_name='Redondear precio a múltiplo de')),
                ('gcode', models.TextField(blank=True, help_text='Pegá acá el g-code del laminador (opcional).', verbose_name='G-code')),
                ('model_file', models.FileField(blank=True, help_text='Subí el .3mf o archivo del modelo (opcional, solo desarrollo local).', upload_to='productos/', verbose_name='Archivo .3mf / modelo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Costeo de producto',
                'verbose_name_plural': 'Costeo de productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad de piezas')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio por pieza guardado al armar el presupuesto. Si se deja vacío, se toma el precio actual del producto. Queda fijo aunque después cambie el costeo del producto.', max_digits=10, null=True, verbose_name='Precio unitario (congelado)')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budgets.presupuesto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_items', to='budgets.producto')),
            ],
            options={
                'verbose_name': 'Producto del presupuesto',
                'verbose_name_plural': 'Productos del presupuesto',
            },
        ),
        migrations.CreateModel(
            name='ProductoAggregateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo por unidad guardado al costear. Si se deja vacío, se toma el precio actual del agregado.', max_digits=10, null=True, verbose_name='Costo por unidad (congelado)')),
                ('aggregate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_lines', to='inventory.aggregate')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_lines', to='budgets.producto')),
            ],
            options={
                'verbose_name': 'Línea de agregado',
                'verbose_name_plural': 'Líneas de agregado',
            },
        ),
        migrations.CreateModel(
            name='ProductoFilamentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gramos usados')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Costo por gramo guardado al momento de costear. Si se deja vacío, se toma el precio actual del filamento.', max_digits=10, null=True, verbose_name='Costo por gramo (congelado)')),
                ('filament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_lines', to='inventory.filament')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filament_lines', to='budgets.producto')),
            ],
            options={
                'verbose_name': 'Línea de filamento',
                'verbose_name_plural': 'Líneas de filamento',
            },
        ),
    ]
