# Generated by Django 6.0.6 on 2026-06-23 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_presupuesto_producto_presupuestoitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at'], 'verbose_name': 'Presupuesto viejo (archivo)', 'verbose_name_plural': 'Presupuestos viejos (archivo)'},
        ),
    ]
