# Generated by Django 6.0.6 on 2026-06-23 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_alter_budget_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoitem',
            name='producto',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_items', to='budgets.producto'),
        ),
    ]
