# Generated by Django 6.0.6 on 2026-06-23 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_alter_presupuestoitem_producto'),
        ('inventory', '0005_remove_stockmovement_related_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetaggregateline',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='budgetfilamentline',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='budgetaggregateline',
            name='aggregate',
        ),
        migrations.RemoveField(
            model_name='budgetfilamentline',
            name='filament',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='BudgetAggregateLine',
        ),
        migrations.DeleteModel(
            name='BudgetFilamentLine',
        ),
    ]
