# Generated by Django 6.0.6 on 2026-06-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_remove_budgetaggregateline_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completado el'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Se calcula sola con la cola de producción. Podés pisarla a mano: si la editás, queda fija y deja de recalcularse.', null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='due_date_is_manual',
            field=models.BooleanField(default=False, verbose_name='Entrega fijada a mano'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='production_finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Producción terminada el'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='production_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Producción iniciada el'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviado el'),
        ),
    ]
