# Generated by Django 6.0.6 on 2026-06-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0010_presupuesto_completed_at_presupuesto_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='is_multicolor',
            field=models.BooleanField(default=False, help_text='Marcá si la pieza usa varios colores/filamentos en simultáneo. Solo se puede imprimir en máquinas con AMS (ej. Bambu Lab), no en la Ender.', verbose_name='Multicolor (AMS)'),
        ),
    ]
