# Generated by Django 6.0.6 on 2026-06-24 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0011_producto_is_multicolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metricas',
            fields=[
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('budgets.presupuesto',),
        ),
    ]
