# Generated by Django 6.0.6 on 2026-06-25 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0012_metricas'),
        ('inventory', '0009_alter_stockmovement_aggregate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la pieza')),
                ('units_needed', models.PositiveIntegerField(default=1, help_text='Cuántas unidades de esta pieza lleva UN producto.', verbose_name='Unidades necesarias por producto')),
                ('pieces_per_gcode', models.PositiveIntegerField(default=1, help_text='Cuántas unidades de esta pieza salen en UNA impresión (un gcode).', verbose_name='Piezas por corrida de gcode')),
                ('print_time_hours', models.DecimalField(decimal_places=2, default=0, help_text='Tiempo de impresión de UNA corrida del gcode (saca `piezas por gcode`).', max_digits=6, verbose_name='Horas de máquina por corrida de gcode')),
                ('requires_ams', models.BooleanField(default=False, help_text='Se marca solo cuando la pieza usa más de una línea de filamento (multicolor): debe ir a una máquina con AMS. Podés forzarlo a mano.', verbose_name='Necesita AMS (multicolor)')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Unidades de esta pieza ya impresas y disponibles en stock.', verbose_name='Stock de piezas impresas')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='budgets.producto')),
            ],
            options={
                'verbose_name': 'Pieza',
                'verbose_name_plural': 'Piezas',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PiezaFilamentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gramos usados (por corrida)')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Costo por gramo guardado al momento de costear. Si se deja vacío, se toma el precio actual del filamento.', max_digits=10, null=True, verbose_name='Costo por gramo (congelado)')),
                ('filament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieza_lines', to='inventory.filament')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filament_lines', to='budgets.pieza')),
            ],
            options={
                'verbose_name': 'Línea de filamento (pieza)',
                'verbose_name_plural': 'Líneas de filamento (pieza)',
            },
        ),
    ]
