# Generated by Django 6.0.6 on 2026-06-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0014_migrate_productos_a_piezas'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPiezas',
            fields=[
            ],
            options={
                'verbose_name': 'Stock de piezas',
                'verbose_name_plural': 'Stock de piezas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('budgets.pieza',),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='print_time_hours',
        ),
        migrations.DeleteModel(
            name='ProductoFilamentLine',
        ),
    ]
