# Generated by Django 6.0.6 on 2026-06-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0015_stockpiezas_remove_producto_print_time_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='stock_provisioned',
            field=models.BooleanField(default=False, help_text='Se marca al aprobar: ya se descontaron las piezas de stock, el filamento y los agregados. Evita descontar dos veces.', verbose_name='Inventario descontado'),
        ),
    ]
