# Generated by Django 6.0.6 on 2026-06-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0016_presupuesto_stock_provisioned'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja'), (9, 'Sin prioridad')], default=9, help_text="Define en qué orden entra a la cola de producción: prioridad más alta se imprime antes. 'Sin prioridad' va al final de la cola.", verbose_name='Prioridad en la cola'),
        ),
    ]
