# Generated by Django 6.0.6 on 2026-06-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0017_producto_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='stock_reversed',
            field=models.BooleanField(default=False, help_text='Se marca al cancelar un pedido aprobado: ya se devolvió al stock el material de lo que no se imprimió, las piezas y los agregados. Evita devolver dos veces.', verbose_name='Inventario devuelto'),
        ),
    ]
