# Generated by Django 6.0.6 on 2026-06-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0018_presupuesto_stock_reversed'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockProductos',
            fields=[
            ],
            options={
                'verbose_name': 'Stock de productos terminados',
                'verbose_name_plural': 'Stock de productos terminados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('budgets.producto',),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='finished_stock_added',
            field=models.BooleanField(default=False, help_text="Se marca al completar un pedido 'para stock': ya se sumaron sus unidades terminadas al stock de productos. Evita sumar dos veces.", verbose_name='Sumado al stock de terminados'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='para_stock',
            field=models.BooleanField(default=False, help_text='Marcá si es producción para tu stock interno, no para un cliente. Funciona igual que un pedido normal (se aprueba, se imprime, se completa); al completarse, las unidades terminadas suman al stock de productos terminados en vez de entregarse.', verbose_name='Pedido para reponer stock (sin cliente)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='min_stock',
            field=models.PositiveIntegerField(default=0, help_text="Cuántas unidades terminadas querés tener siempre en stock. Si el stock baja de este número, el producto aparece como 'a reponer'. 0 = no se controla el mínimo.", verbose_name='Stock mínimo de terminados'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Unidades de este producto ya terminadas (armadas) y disponibles para entregar sin imprimir. Sube al completar un pedido de stock.', verbose_name='Stock de productos terminados'),
        ),
    ]
