# Generated by Django 6.0.6 on 2026-06-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0019_stockproductos_presupuesto_finished_stock_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestoitem',
            name='from_finished_stock',
            field=models.PositiveIntegerField(default=0, help_text='Unidades de esta línea que se sirvieron del stock de productos terminados al aprobar (no se produjeron). Se usa para devolver el stock si el pedido se cancela.', verbose_name='Servido del stock de terminados'),
        ),
    ]
