# Generated by Django 6.0.6 on 2026-09-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0020_presupuestoitem_from_finished_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='diseno_listo',
            field=models.BooleanField(default=False, help_text='Marcá cuando el modelo/gcode ya está terminado y revisado, listo para que producción lo tenga en cuenta al imprimir.', verbose_name='Diseño listo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='diseno_listo_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Diseño marcado listo el'),
        ),
    ]
