# Generated by Django 6.0.6 on 2026-09-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0021_producto_diseno_listo_producto_diseno_listo_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='machine_cost_per_hour',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10, verbose_name='Costo de máquina por hora'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='waste_percent',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Desperdicio de filamento por purga (multicolor), soportes y fallas. Se aplica sobre el costo y el consumo de material.', max_digits=5, verbose_name='Merma de material (%)'),
        ),
    ]
