# Generated by Django 6.0.6 on 2026-09-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0022_alter_producto_machine_cost_per_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='post_processing_hours',
        ),
        migrations.AddField(
            model_name='producto',
            name='post_processing_minutes',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Tiempo de armado, lijado, pintado, pegado de agregados, etc.', max_digits=7, verbose_name='Post-proceso por pieza (min)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='labor_cost_per_hour',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='Costo de mano de obra por hora'),
        ),
    ]
