# Generated by Django 6.0.6 on 2026-09-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0023_remove_producto_post_processing_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='margin_percent',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='round_to',
        ),
        migrations.AddField(
            model_name='producto',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio final al que se vende UNA unidad. Se carga a mano en base al costo (ver arriba); no se recalcula solo si cambian los costos.', max_digits=10, verbose_name='Precio de venta'),
        ),
    ]
