# Generated by Django 6.0.6 on 2026-09-21 21:02
# Editado a mano: el campo pasa de horas a minutos, así que convertimos los
# valores existentes (× 60) en vez de perderlos.

from decimal import Decimal

from django.db import migrations, models


def horas_a_minutos(apps, schema_editor):
    Pieza = apps.get_model("budgets", "Pieza")
    for pieza in Pieza.objects.exclude(print_time_hours=0):
        pieza.print_time_minutes = pieza.print_time_hours * Decimal("60")
        pieza.save(update_fields=["print_time_minutes"])


def minutos_a_horas(apps, schema_editor):
    Pieza = apps.get_model("budgets", "Pieza")
    for pieza in Pieza.objects.exclude(print_time_minutes=0):
        pieza.print_time_hours = pieza.print_time_minutes / Decimal("60")
        pieza.save(update_fields=["print_time_hours"])


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0024_remove_producto_margin_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='print_time_minutes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tiempo de impresión de UNA corrida del gcode (saca `piezas por gcode`).', max_digits=8, verbose_name='Minutos de máquina por corrida de gcode'),
        ),
        migrations.RunPython(horas_a_minutos, minutos_a_horas),
        migrations.RemoveField(
            model_name='pieza',
            name='print_time_hours',
        ),
    ]
