# Generated by Django 6.0.6 on 2026-09-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0025_remove_pieza_print_time_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieza',
            name='requires_ams',
            field=models.BooleanField(default=False, help_text='Marcala si la pieza usa más de una línea de filamento (multicolor): debe ir a una máquina con AMS. Con esto marcado hacen falta 2 o más líneas de filamento; sin marcar, no puede haber más de una.', verbose_name='Necesita AMS (multicolor)'),
        ),
    ]
