# Generated by Django 6.0.6 on 2026-09-29 01:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0026_alter_pieza_requires_ams'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Agregada el'),
            preserve_default=False,
        ),
    ]
