# Generated by Django 6.0.6 on 2026-09-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0027_pieza_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelVentas',
            fields=[
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Panel de ventas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('budgets.presupuesto',),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='estado_venta',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('PARCIAL', 'Pago parcial'), ('PAGADO', 'Pagado')], default='PENDIENTE', help_text='Si el cliente ya pagó este pedido. Es independiente del estado de producción (un pedido puede estar Aprobado o Completado y seguir Pendiente de pago).', max_length=20, verbose_name='Estado de venta'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MERCADOPAGO', 'Mercado Pago'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], default='', help_text='Cómo pagó (o va a pagar) el cliente. Se puede dejar vacío.', max_length=20, verbose_name='Método de pago'),
        ),
    ]
