# Generated by Django 6.0.6 on 2026-09-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0028_panelventas_presupuesto_estado_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MERCADOPAGO', 'Mercado Pago'), ('UALA', 'Ualá'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], default='', help_text='Cómo pagó (o va a pagar) el cliente. Se puede dejar vacío.', max_length=20, verbose_name='Método de pago'),
        ),
    ]
