# Generated by Django 6.0.6 on 2026-09-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0029_alter_presupuesto_medio_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricasVentas',
            fields=[
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Panel de ventas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('budgets.presupuesto',),
        ),
        migrations.CreateModel(
            name='PanelCostos',
            fields=[
            ],
            options={
                'verbose_name': 'Costo',
                'verbose_name_plural': 'Panel de costos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('budgets.presupuesto',),
        ),
        migrations.AlterModelOptions(
            name='metricas',
            options={'verbose_name': 'Métrica', 'verbose_name_plural': 'Panel de métricas'},
        ),
        migrations.AlterModelOptions(
            name='panelventas',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
