# Generated by Django 6.0.6 on 2026-09-30 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0030_metricasventas_panelcostos_alter_metricas_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='% del beneficio neto del período que le corresponde a este socio.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de participación')),
                ('is_active', models.BooleanField(default=True, help_text='Los socios inactivos no aparecen en la Distribución de ingresos.', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'ordering': ['order', 'name'],
            },
        ),
    ]
