# Generated by Django 6.0.6 on 2026-10-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0031_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelCaja',
            fields=[
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Panel de caja',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('budgets.presupuesto',),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_cobro',
            field=models.DateField(blank=True, help_text='Cuándo entró realmente la plata (puede ser bien distinta de la fecha de aprobación). Se completa sola al marcar "Pagado" si está vacía, pero se puede ajustar a mano. La usa el Panel de caja para medir cobros reales por fecha, no por aprobación.', null=True, verbose_name='Fecha de cobro'),
        ),
    ]
