# Generated by Django 6.0.6 on 2026-10-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0033_backfill_fecha_cobro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PanelCaja',
        ),
    ]
