# Generated by Django 6.0.6 on 2026-10-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0034_delete_panelcaja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Costeo de producto', 'verbose_name_plural': 'Costeo de productos'},
        ),
    ]
