# Generated by Django 6.0.6 on 2026-10-05 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0035_alter_producto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.CharField(help_text='external_reference de la Order en 3darg-backend (y de la preferencia de MercadoPago). Sirve para no duplicar el aviso si el webhook de origen reintenta.', max_length=80, unique=True, verbose_name='Referencia externa')),
                ('brand_slug', models.CharField(max_length=50, verbose_name='Marca (slug)')),
                ('brand_name', models.CharField(blank=True, max_length=150, verbose_name='Marca')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del cliente')),
                ('items', models.JSONField(blank=True, default=list, help_text='Snapshot de los items comprados: [{product_name, quantity, unit_price}, ...].', verbose_name='Productos')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('currency', models.CharField(default='ARS', max_length=10, verbose_name='Moneda')),
                ('order_created_at', models.DateTimeField(blank=True, help_text='Cuándo se creó la Order en la tienda, no cuándo llegó este aviso.', null=True, verbose_name='Fecha de la orden')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Recibido')),
                ('revisado', models.BooleanField(default=False, help_text='Marcalo una vez que ya lo cargaste (o decidiste no cargarlo).', verbose_name='Revisado')),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Body completo recibido de 3darg-backend, para auditoría/debug.', verbose_name='Payload crudo')),
                ('presupuesto', models.ForeignKey(blank=True, help_text='Si lo cargaste como presupuesto, enlazalo acá (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_online', to='budgets.presupuesto', verbose_name='Presupuesto cargado')),
            ],
            options={
                'verbose_name': 'Pedido online pendiente',
                'verbose_name_plural': 'Pedidos online pendientes',
                'ordering': ['-received_at'],
            },
        ),
    ]
