# Generated by Django 6.0.6 on 2026-10-07 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0036_pedidoonline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Canal')),
                ('comision_percent', models.DecimalField(decimal_places=2, default=0, help_text='Comisión que cobra el canal sobre el precio de venta (ej: comisión de Mercado Libre, variable según categoría).', max_digits=5, verbose_name='Comisión del canal (%)')),
                ('costo_fijo', models.DecimalField(decimal_places=2, default=0, help_text='Cargo fijo que cobra el canal por cada venta, sin importar el monto (ej: el cargo fijo de Mercado Libre en ventas de bajo monto).', max_digits=10, verbose_name='Cargo fijo por venta')),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, help_text="Costo de envío que asumís como vendedor en este canal, si aplica. Se puede pisar por producto en 'Gastos de venta y precio por canal' si uno en particular pesa/mide distinto.", max_digits=10, verbose_name='Costo de envío promedio')),
                ('otros_costos_percent', models.DecimalField(decimal_places=2, default=0, help_text='Otros costos variables del canal sobre el precio de venta (impuestos, pasarela de pago, etc.).', max_digits=5, verbose_name='Otros costos variables (%)')),
                ('is_active', models.BooleanField(default=True, help_text='Los canales inactivos dejan de sumarse solos a los productos nuevos, pero no borran los precios por canal ya cargados.', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Canal de venta',
                'verbose_name_plural': 'Canales de venta',
                'ordering': ['order', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoCanalPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Si se deja vacío, se usa el precio de venta general del producto (pestaña Precio).', max_digits=10, null=True, verbose_name='Precio de venta en este canal')),
                ('costo_envio_override', models.DecimalField(blank=True, decimal_places=2, help_text='Si este producto tiene un costo de envío distinto al promedio del canal (por peso/tamaño), cargalo acá. Vacío = usa el costo de envío general del canal.', max_digits=10, null=True, verbose_name='Costo de envío de este producto')),
                ('notas', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_precios', to='budgets.canalventa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canal_precios', to='budgets.producto')),
            ],
            options={
                'verbose_name': 'Precio por canal',
                'verbose_name_plural': 'Precios por canal',
                'ordering': ['canal__order', 'canal__nombre'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'canal'), name='unique_producto_canal')],
            },
        ),
    ]
