# Generated by Django 6.0.6 on 2026-10-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0038_seed_canales_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, help_text="Código único de catálogo, el mismo que usa este producto en la página web y en Mercado Libre (se autogenera ahí como '3DARG-000123', ver `Product.sku` en el backend de la web). Cargalo a mano acá para poder ubicar rápido a qué costeo corresponde cada venta. Opcional: dejalo vacío si el producto todavía no se publicó en ningún canal.", max_length=64, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
