# Generated by Django 6.0.6 on 2026-10-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0039_producto_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, help_text="Código único de catálogo, el mismo que usa este producto en la página web y en Mercado Libre (se autogenera ahí con el formato 'MARCA-CATEGORIA-NNNNNN', ej. 'LUMY-COR-000037', opcionalmente con '-COLOR-TAMAÑO' al final si el producto los tiene cargados; ver `Product.generate_sku()` en el backend de la web). Cargalo a mano acá para poder ubicar rápido a qué costeo corresponde cada venta. Opcional: dejalo vacío si el producto todavía no se publicó en ningún canal.", max_length=64, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
