# Generated by Django 6.0.6 on 2026-10-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0040_alter_producto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ecommerce_cutter_size',
            field=models.CharField(blank=True, choices=[('mini', 'Mini'), ('chico', 'Chico'), ('mediano', 'Mediano'), ('grande', 'Grande'), ('a_medida', 'A medida')], help_text="Obligatorio si 'Es producto de ecommerce' está marcado — es la clave que usa 3darg-backend para saber a qué productos de catálogo les toca este precio/medidas (tiene que ser el mismo tamaño que tengan cargado ahí en 'Tamaño de cortante').", max_length=20, verbose_name='Tamaño (3darg-backend)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_producto_ecommerce',
            field=models.BooleanField(default=False, help_text='Marcá esto cuando este costeo representa un tamaño compartido por muchos diseños del catálogo de 3darg-backend (ej: "cortante mediano", no un diseño puntual). Al guardar con esto activo, se le avisa a 3darg-backend para que actualice en bloque el precio y las medidas de TODOS los productos de catálogo que tengan cargado ese mismo tamaño (\'Tamaño (3darg-backend)\' abajo) — y, si ya están publicados en Mercado Libre, los vuelve a publicar con los valores nuevos, sin tener que entrar al otro admin. Categoría, SKU y el resto de los datos propios de cada diseño NO se tocan: eso sigue siendo manual en 3darg-backend.', verbose_name='Es producto de ecommerce'),
        ),
        migrations.AddField(
            model_name='producto',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Alto (cm)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Largo (cm)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Mismo campo que `Product.weight_kg` en 3darg-backend (lo usa Mercado Libre para calcular el envío) — se sincroniza tal cual, sin conversión.', max_digits=6, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ancho (cm)'),
        ),
    ]
