# Generated by Django 6.0.6 on 2026-10-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0041_producto_ecommerce_cutter_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocanalprecio',
            name='comision_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si este producto paga una comisión distinta a la del canal (otra categoría de Mercado Libre, por ejemplo), cargala acá. Vacío = usa la comisión general del canal.', max_digits=5, null=True, verbose_name='Comisión en este producto (%)'),
        ),
        migrations.AddField(
            model_name='productocanalprecio',
            name='costo_fijo_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si este producto paga un cargo fijo por venta distinto al del canal (el cargo fijo de Mercado Libre es escalonado por precio), cargalo acá. Vacío = usa el cargo fijo general del canal.', max_digits=10, null=True, verbose_name='Cargo fijo en este producto'),
        ),
        migrations.AddField(
            model_name='productocanalprecio',
            name='otros_costos_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si este producto tiene otros costos variables distintos al promedio del canal (ej: ofrecés un plan de cuotas distinto en esta publicación), cargalo acá. Vacío = usa el valor general del canal.', max_digits=5, null=True, verbose_name='Otros costos variables en este producto (%)'),
        ),
    ]
