# Generated by Django 6.0.6 on 2026-10-09 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0042_agregar_overrides_comision_cargo_fijo_otros_costos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canalventa',
            name='costo_fijo',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Cargo fijo plano para este canal. Si cargás 'Tramos de cargo fijo' más abajo, el sistema calcula el cargo fijo solo según el precio de cada producto y este valor queda como respaldo (se usa solo si el precio de un producto no cae en ningún tramo cargado).", max_digits=10, verbose_name='Cargo fijo por venta (default)'),
        ),
        migrations.CreateModel(
            name='CanalCargoFijoTramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_desde', models.DecimalField(decimal_places=2, help_text='Este tramo aplica a partir de este precio (incluido). Cargá el tramo de precio más bajo con $0.', max_digits=10, verbose_name='Precio desde')),
                ('precio_hasta', models.DecimalField(blank=True, decimal_places=2, help_text='Hasta este precio, sin incluirlo. Dejalo vacío en el último tramo (sin techo, ej: $33.000 en adelante).', max_digits=10, null=True, verbose_name='Precio hasta')),
                ('cargo_fijo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cargo fijo en este tramo')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos_cargo_fijo', to='budgets.canalventa')),
            ],
            options={
                'verbose_name': 'Tramo de cargo fijo',
                'verbose_name_plural': 'Tramos de cargo fijo',
                'ordering': ['canal', 'precio_desde'],
            },
        ),
    ]
