# Generated by Django 6.0.6 on 2026-10-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0043_agregar_tramos_cargo_fijo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ecommerce_cutter_size',
        ),
        migrations.AddField(
            model_name='producto',
            name='ecommerce_template_name',
            field=models.CharField(blank=True, help_text='Obligatorio si \'Es producto de ecommerce\' está marcado. Nombre libre del template de costo compartido (ej: "Cortante 4cm", "Shaker grande") — no hace falta que coincida con ningún valor fijo. La sincronización usa una referencia interna estable (el ID de este Producto) para encontrar el template del lado de 3darg-backend, así que renombrarlo acá más adelante no rompe el link ya hecho.', max_length=100, verbose_name='Nombre del template (3darg-backend)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='es_producto_ecommerce',
            field=models.BooleanField(default=False, help_text='Marcá esto cuando este costeo representa un presupuesto compartido por muchos diseños del catálogo de 3darg-backend (ej: "Cortante 4cm", "Shaker grande"), no un diseño puntual. Al guardar con esto activo, se le avisa a 3darg-backend para que cree o actualice el template de costo correspondiente (\'Nombre del template\' abajo) con el precio y las medidas de acá — y republique en Mercado Libre los productos de catálogo que ya estén vinculados a ese template. Qué diseños/variantes quedan vinculados a cada template se elige a mano desde el admin de 3darg-backend, no se toca desde acá.', verbose_name='Es producto de ecommerce'),
        ),
    ]
