# Generated by Django 6.0.6 on 2026-10-03 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0034_delete_panelcaja'),
        ('gastos', '0006_gasto_cuota_actual_gasto_cuotas_totales'),
        ('inventory', '0015_aggregatecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Monto real que esta cuenta tenía al momento de arrancar a usarla en el sistema, para no empezar en $0 artificial.', max_digits=12, verbose_name='Saldo inicial')),
                ('fecha_saldo_inicial', models.DateField(help_text='Desde cuándo vale el saldo inicial. Los movimientos confirmados se suman desde esta fecha en adelante.', verbose_name='Fecha del saldo inicial')),
                ('medio_pago_default', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MERCADOPAGO', 'Mercado Pago'), ('UALA', 'Ualá'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], default='', help_text='Si esta cuenta recibe los cobros/pagos de un medio de pago puntual (ej: Efectivo, Mercado Pago), configuralo acá para que el sistema arme solo el borrador de caja al marcar un presupuesto como Pagado con ese medio. Dejalo vacío si esta cuenta no recibe autogeneración.', max_length=20, verbose_name='Medio de pago que recibe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Cuenta de caja',
                'verbose_name_plural': 'Cuentas de caja',
                'ordering': ['order', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha real del movimiento de plata (no la fecha del documento de origen, si tiene uno).', verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Siempre positivo; el signo lo da el tipo (Ingreso/Egreso).', max_digits=12, verbose_name='Monto')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('DESCARTADO', 'Descartado')], default='CONFIRMADO', help_text='Los movimientos cargados a mano nacen Confirmados. Los que genera el sistema automáticamente nacen en Borrador, para revisarlos y confirmarlos antes de que afecten el saldo real.', max_length=10, verbose_name='Estado')),
                ('origen_automatico', models.BooleanField(default=False, help_text='Si lo generó el sistema (a diferencia de cargado a mano).', verbose_name='Generado automáticamente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='inventory.compra', verbose_name='Compra')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.cuentacaja', verbose_name='Cuenta')),
                ('gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='gastos.gasto', verbose_name='Gasto')),
                ('presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='budgets.presupuesto', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PanelCaja',
            fields=[
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Panel de caja',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.movimientocaja',),
        ),
    ]
