# Generated by Django 6.0.6 on 2026-10-03 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('production', '0012_herramientacategoria_herramienta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='herramienta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='production.herramienta', verbose_name='Herramienta'),
        ),
    ]
