# Generated by Django 6.0.6 on 2026-06-28 15:44

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('ADMIN', 'Administración'), ('COMMERCIAL', 'Comercialización'), ('SUBSCRIPTION', 'Suscripciones'), ('IT', 'IT'), ('OTHER', 'Otro')], default='ADMIN', max_length=20, verbose_name='Categoría')),
                ('concepto', models.CharField(help_text='Qué gasto es (ej: Contador, Google Workspace, Publicidad Instagram).', max_length=150, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto ($)')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, help_text='Fecha del gasto. Define en qué mes/año cae en el panel.', verbose_name='Fecha')),
                ('proveedor', models.CharField(blank=True, max_length=150, verbose_name='Proveedor')),
                ('medio_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta de crédito'), ('DEBITO', 'Débito automático'), ('OTRO', 'Otro')], max_length=20, verbose_name='Medio de pago')),
                ('es_recurrente', models.BooleanField(default=False, help_text='Marcalo si es un gasto fijo que se repite (suscripción, abono). Se usa para calcular el compromiso mensual (run-rate).', verbose_name='Es recurrente')),
                ('periodicidad', models.CharField(choices=[('UNICA', 'Único (no se repite)'), ('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], default='UNICA', help_text='Si es recurrente, cada cuánto se paga (para el compromiso mensual).', max_length=10, verbose_name='Periodicidad')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TopeGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('ADMIN', 'Administración'), ('COMMERCIAL', 'Comercialización'), ('SUBSCRIPTION', 'Suscripciones'), ('IT', 'IT'), ('OTHER', 'Otro')], max_length=20, unique=True, verbose_name='Categoría')),
                ('monto_mensual', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Gasto máximo esperado por mes para esta categoría. 0 = sin tope.', max_digits=12, verbose_name='Tope mensual ($)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Tope de gasto (presupuesto)',
                'verbose_name_plural': 'Topes de gasto (presupuestos)',
                'ordering': ['categoria'],
            },
        ),
        migrations.CreateModel(
            name='PanelGastos',
            fields=[
            ],
            options={
                'verbose_name': 'Panel de gastos',
                'verbose_name_plural': 'Panel de gastos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gastos.gasto',),
        ),
    ]
