# Generated by Django 6.0.6 on 2026-09-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(choices=[('OPERATIVO', 'Operativo (estructura del negocio)'), ('EXTRAORDINARIO', 'Extraordinario (puntual, no representativo)')], default='OPERATIVO', help_text='Operativo: gasto de estructura del negocio (entra en el resultado operativo vs ventas). Extraordinario: gasto puntual y no representativo (viajes, imprevistos) que se muestra aparte para no distorsionar el resultado.', max_length=20, verbose_name='Tipo'),
        ),
    ]
