# Generated by Django 6.0.6 on 2026-09-29 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_categoriagasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Área responsable',
                'verbose_name_plural': 'Áreas responsables',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Área del negocio responsable del gasto (opcional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='gastos.arearesponsable', verbose_name='Área responsable'),
        ),
    ]
