# Generated by Django 6.0.6 on 2026-09-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_mediopagogasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='cuota_actual',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Si este gasto es una cuota de un plan de pagos (ej: una impresora en 12 cuotas), qué número de cuota es este pago puntual (ej: 4 si es la cuota 4 de 12). Se usa junto con "Cuotas totales".', null=True, verbose_name='Cuota actual'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='cuotas_totales',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cuántas cuotas tiene el plan de pagos en total. Completalo junto con "Cuota actual" para que la proyección anual del compromiso mensual no siga contando este gasto después de terminar de pagarse. Dejalo vacío si no aplica (gasto recurrente indefinido).', null=True, verbose_name='Cuotas totales'),
        ),
    ]
